name: "Check project health"
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Gradle build app
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
